name: ktor
summary: Creates porjects with ktor framework setup
version: '2.0.0-eap-1'
base: core18
grade: stable
confinement: strict
description: |
  Ktor is a web application framework for creating connected systems.
  You can use it to create server-side as well as client-side applications.
  It supports multiple platforms, including JVM, JavaScript, and Kotlin/Native.
  This CLI tool provides functionality to create new Ktor projects.
apps:
  ktor:
    command: ktor
parts:
  ktor:
    plugin: nil
    build-packages:
      - wget
    override-pull: |
      snapcraftctl pull
      wget https://files.pkg.jetbrains.space/public/p/ktor-cli-tool/linux-release/ktor-cli-generator.kexe
    override-install: |
      snapcraftctl install
      cp ktor-cli-generator.kexe $SNAPCRAFT_PART_INSTALL/ktor
