name: ktor
base: core24
version: 'dev'
summary: Generates Ktor projects through the command line interface.
website: https://github.com/ktorio/ktor-cli
license: Apache-2.0
description: |
  This CLI tool allows generating server-side projects written with Ktor.
  Ktor is an asynchronous framework for creating client and server applications, from microservices to multiplatform client apps.
  Written in Kotlin from the ground up.

grade: stable
confinement: strict
adopt-info: ktor

platforms:
  amd64:
  arm64:
    build-on: [amd64]
    build-for: [arm64]

apps:
  ktor:
    command: bin/ktor
    plugs:
      - home
      - network

parts:
  ktor:
    plugin: nil
    source: https://github.com/ktorio/ktor-cli.git
    source-type: git
    override-build: |
      export GOBIN="${CRAFT_PART_INSTALL}/bin"
      export CGO_ENABLED=0
      go mod download
      go install -ldflags="-X main.Version=$(git describe --tags --contains --always --abbrev=7)" ./...
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --contains --always --abbrev=7)
    build-snaps:
      - go
