#file: noinspection YAMLSchemaValidation
name: ktor
base: core24
version: 'dev'
summary: Generates Ktor applications through the command line interface.
description: |
  Ktor is an asynchronous framework for creating microservices, web applications and more.
  Written in Kotlin from the ground up.

grade: stable
confinement: strict
adopt-info: ktor

platforms:
  amd64:
  arm64:
    build-on: [amd64]
    build-for: [arm64]

apps:
  ktor:
    command: bin/ktor
    plugs:
      - home
      - network

parts:
  ktor:
    plugin: go
    source: https://github.com/ktorio/ktor-cli.git
    source-type: git
    go-buildtags: -X main.Version=dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --contains --always --abbrev=10)
    build-snaps:
      - go
