name: ktor # you probably want to 'snapcraft register <name>'
summary: Creates porjects with ktor framework setup.
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
icon: gui/ktorPlugin.svg
base: core18
grade: stable
confinement: strict
description: |
  Ktor is a web application framework for creating connected systems. 
  You can use it to create server-side as well as client-side applications. 
  It supports multiple platforms, including JVM, JavaScript, and Kotlin/Native. 
  This CLI tool provides functionality to create new Ktor projects.
apps:
  ktor:
    command: build/bin/linuxX64/releaseExecutable/ktor-cli-generator.kexe
parts:
  ktor:
    plugin: gradle
    source: https://github.com/ktorio/ktor-cli/archive/refs/tags/0.0.1-tmp-3.tar.gz
    gradle-options: [linkReleaseExecutableLinuxX64]
    build-packages:
      - curl
      - unzip
    stage-packages:
      - git
